"use server";

import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { requireUser } from "@/server/auth";
import { prisma } from "@/server/db";
import { writeAuditLog } from "@/server/audit";
import { getOrgSettings } from "@/server/settings";
import { campaignStrategySchema, generateCampaignStrategy, estimateStrategyCostUsd, type CampaignStrategy } from "@/server/strategy";

export async function createProduct(input: { name: string; type: "product" | "service"; summary: string }) {
  const user = await requireUser();
  const product = await prisma.product.create({
    data: { organizationId: user.organizationId, name: input.name, type: input.type, summary: input.summary },
  });
  return product;
}

export async function estimateNewCampaignCostUsd(input: {
  productName: string;
  productType: "product" | "service";
  productSummary: string;
  location?: string;
  buyerGuess?: string;
  goal?: string;
}) {
  return estimateStrategyCostUsd(input);
}

export async function createCampaign(input: {
  productId: string;
  name: string;
  ownerId?: string;
  location?: string;
  goal?: string;
  buyerGuess?: string;
}) {
  const user = await requireUser();
  const settings = await getOrgSettings();
  const ownerId = user.role === "rep" ? user.id : input.ownerId || user.id;

  const [product, existingCampaigns] = await Promise.all([
    prisma.product.findFirstOrThrow({ where: { id: input.productId, organizationId: user.organizationId } }),
    prisma.campaign.findMany({ where: { productId: input.productId, organizationId: user.organizationId }, select: { name: true, location: true } }),
  ]);

  const generated = await generateCampaignStrategy({
    organizationId: user.organizationId,
    userId: user.id,
    productName: product.name,
    productType: product.type,
    productSummary: product.summary,
    location: input.location,
    buyerGuess: input.buyerGuess,
    goal: input.goal,
    existingCampaigns: existingCampaigns.map((c) => `${c.name} (${c.location ?? "no location set"})`).join("; ") || undefined,
  });

  // No approval gate: a campaign goes live the moment its creator approves the playbook.
  const campaign = await prisma.campaign.create({
    data: {
      organizationId: user.organizationId,
      productId: product.id,
      name: input.name,
      ownerId,
      status: "active",
      goal: input.goal,
      location: input.location,
      strategy: generated.strategy as unknown as object,
      leadDailyCap: settings.leadDailyCapDefault,
      approvedById: user.id,
      approvedAt: new Date(),
    },
  });

  await prisma.campaignNote.create({
    data: {
      organizationId: user.organizationId,
      campaignId: campaign.id,
      authorId: user.id,
      kind: "system",
      body:
        generated.source === "ai"
          ? `Playbook generated by ${settings.assistantName} (prompt v${generated.promptVersion}).`
          : `Playbook generated from a template — AI was unavailable (${generated.reason}).`,
    },
  });

  await writeAuditLog({
    organizationId: user.organizationId,
    actorId: user.id,
    action: "campaign_created",
    entityType: "campaign",
    entityId: campaign.id,
    after: { name: campaign.name, status: campaign.status, strategySource: generated.source },
  });

  revalidatePath("/campaigns");
  redirect(`/campaigns/${campaign.id}`);
}

async function assertCanEditCampaign(campaignId: string) {
  const user = await requireUser();
  const campaign = await prisma.campaign.findFirst({ where: { id: campaignId, organizationId: user.organizationId } });
  if (!campaign) throw new Error("Campaign not found");
  if (user.role === "rep" && campaign.ownerId !== user.id) throw new Error("Not your campaign");
  return { user, campaign };
}

export async function updateCampaignStrategy(campaignId: string, strategy: CampaignStrategy) {
  const { user, campaign } = await assertCanEditCampaign(campaignId);
  const parsed = campaignStrategySchema.parse(strategy);

  await prisma.campaign.update({
    where: { id: campaignId },
    data: { strategy: parsed as unknown as object, strategyVersion: { increment: 1 } },
  });
  await prisma.campaignNote.create({
    data: {
      organizationId: user.organizationId,
      campaignId,
      authorId: user.id,
      kind: "system",
      body: `Playbook updated (now version ${campaign.strategyVersion + 1}).`,
    },
  });
  revalidatePath(`/campaigns/${campaignId}`);
}

export async function rethinkStrategy(campaignId: string, changeRequest?: string) {
  const { user, campaign } = await assertCanEditCampaign(campaignId);
  const product = await prisma.product.findUniqueOrThrow({ where: { id: campaign.productId } });
  const generated = await generateCampaignStrategy({
    organizationId: user.organizationId,
    userId: user.id,
    productName: product.name,
    productType: product.type,
    productSummary: product.summary,
    location: campaign.location ?? undefined,
    goal: campaign.goal ?? undefined,
    currentStrategy: campaignStrategySchema.parse(campaign.strategy),
    changeRequest,
  });
  return generated;
}

export async function addCampaignNote(campaignId: string, body: string) {
  const { user } = await assertCanEditCampaign(campaignId);
  await prisma.campaignNote.create({
    data: { organizationId: user.organizationId, campaignId, authorId: user.id, kind: "note", body },
  });
  revalidatePath(`/campaigns/${campaignId}`);
}

export async function pauseCampaign(campaignId: string, reason: string) {
  const { user } = await assertCanEditCampaign(campaignId);
  await prisma.campaign.update({ where: { id: campaignId }, data: { status: "paused", pausedReason: reason } });
  await writeAuditLog({
    organizationId: user.organizationId,
    actorId: user.id,
    action: "campaign_paused",
    entityType: "campaign",
    entityId: campaignId,
    after: { reason },
  });
  revalidatePath(`/campaigns/${campaignId}`);
  revalidatePath("/campaigns");
}

export async function resumeCampaign(campaignId: string) {
  const { user } = await assertCanEditCampaign(campaignId);
  await prisma.campaign.update({ where: { id: campaignId }, data: { status: "active", pausedReason: null } });
  await writeAuditLog({
    organizationId: user.organizationId,
    actorId: user.id,
    action: "campaign_resumed",
    entityType: "campaign",
    entityId: campaignId,
  });
  revalidatePath(`/campaigns/${campaignId}`);
  revalidatePath("/campaigns");
}

export async function archiveCampaign(campaignId: string) {
  const { user } = await assertCanEditCampaign(campaignId);
  await prisma.campaign.update({ where: { id: campaignId }, data: { status: "archived" } });
  await writeAuditLog({
    organizationId: user.organizationId,
    actorId: user.id,
    action: "campaign_archived",
    entityType: "campaign",
    entityId: campaignId,
  });
  revalidatePath(`/campaigns/${campaignId}`);
  revalidatePath("/campaigns");
}
